# Generated by Django 2.0 on 2018-03-24 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180317_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='joined_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='the date and time when the event was created'),
        ),
    ]
