# Generated by Django 2.0 on 2018-03-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20180324_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='times_flagged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
