# Generated by Django 2.0 on 2018-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_add_event_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseries',
            name='end_time',
            field=models.TimeField(db_index=True, help_text='Local time that the event ends', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='start_time',
            field=models.TimeField(db_index=True, help_text='Local time that the event starts', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
