# Generated by Django 2.0 on 2018-05-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20180417_2308'),
        ('events', '0029_add_team_premium_fields'),
    ]

    operations = [
    ]
