# Generated by Django 2.0 on 2018-05-05 02:20

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_merge_20180501_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='cover_img',
        ),
        migrations.AddField(
            model_name='team',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='cover_images', verbose_name='Cover Image'),
        ),
    ]
