# Generated by Django 2.0 on 2018-05-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20180505_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='cover_image',
            new_name='cover_img',
        ),
    ]
